name: "Hass Addon for RabbitMQ"
description: "A home assistant addon for the RabbitMQ message broker"
version: "3.11.7-p2"
slug: "rabbitmq"
init: false
arch:
  - amd64
  - aarch64
options:
  password: "pleasechange"
schema:
  password: "password"
