name: "Beancount Accounting"
description: "Beancount Double-Entry Accounting Software (v2)"
version: "2.3.5"
slug: "beancount-2"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options: {}
schema: {}
ingress: 5000
ingress_port: 5000
ingress_entry: "/discover"
hassio_api: true
panel_icon: "mdi:octagram"
map:
  - "share:rw"
