name: "Hassio Addon for Postgres"
description: "An add for Postgres configured to support taiga"
version: "13.9-p3"
slug: "taiga_postgres"
init: false
arch:
  - amd64
  - aarch64
options:
  initial_password: "pleasechange"
schema:
  initial_password: "password"
